@startuml
node "Display" <<Device>> as Display {
 component "Web Browser" as Browser {
 }
}

    node "App System" as Docker {
                component Backend as NestJS {
                }

                component "Process and Storage Unit" as SUpro{
                }
                database Cache{
                }

                database Database {
                }
                component Collecteurs {
                }
                component Frontend {
                }


    }

cloud "Api Keolis" <<API>> as keo{
}
cloud "Api SNCF" <<API>> as SNCF{
}
cloud "Api Navitia.io" <<API>> as Nav{
}


Frontend #-# Browser : HTTP
NestJS #-# Cache
Collecteurs #-# SUpro
SUpro #--# Database
SUpro #-# NestJS
NestJS #--# Frontend

keo <-->  Collecteurs: HTTP
SNCF <-->  Collecteurs: HTTP
Nav  <--> Collecteurs : HTTP

@enduml
